### ISSUE TITLE
Not working with Fooocus-MRE

### ISSUE THREAD

**Issue by barepixels** [mattmarkwick/fooocus-gallery#6]
So I finally tried out fooocus-galley and WOW you did a fantastic job.  
It works great with lllyasviel Fooocus but fails when I open the log.html from https://github.com/MoonRide303/Fooocus-MRE/ (my prefer fork) Can you please look into it.

Also a request, can you add a delete button next to the expand button?  It would be great to be able to purge bad images (deform hands, limbs, just very obviously bad images.)  While reviewing a fresh batch.  There are no reasons to keep them.

**Comment by mattmarkwick** [comment]
Well thanks very much, I appreciate that! Honestly I didn't think anybody was really using it! 

I've never used MoonRide's fork but perhaps I could take a look at this. I'm about to go on holiday but when I get back I'll see whether this is possible. 

The delete button is unfortunately not possible for this version - as this is just Javascript running in Tampermonkey it doesn't have write access to your computer (for security reasons). I had started looking at building a more featured app to provide this functionality and more, but it lost momentum as life takes over. I'd like to have another stab at that sometime, I may one day get around to it...

**Comment by barepixels** [comment]
Oh you must try MoonRide's fork.  It is far superior.  Example
Metatag is embedded into the  PNG.  Fooocus-MRE can load the settings back
Settings, resolutions, styles are external and can be custom-config to your liking
Can generate forever... till you want to stop.  This allows Fooocus working all night while you sleep or all day while you are at work.  I find with Stabble Diffussion it is a number game.  Generate 500 while you sleep then pick the best few to keep in the morning.  Easy Peasy

Fooocus-MRE has much more feature then lllyasviel Fooocus.  I work hard in begging MoonRide to make these modifications.  lolol

**Comment by mattmarkwick** [comment]
Hi, sorry I've taken literal months to get around to this but I simply haven't had the time available. I've finally fixed the fooocus gallery to support the latest version of Fooocus. I've taken a quick look at the MRE fork and it seems it has not been updated to match the new format of the private log in OG Fooocus, so this will not be compatible.
