### ISSUE TITLE
Errors in the bundle.js script code

### ISSUE THREAD

**Issue by kkol4anov** [mattmarkwick/fooocus-gallery#7]
There are many errors in the bundle.js script code. So it does not work.

Screenshot was made in the Tempermonkey editor:
![image](https://github.com/mattmarkwick/fooocus-gallery/assets/39926218/c00a6efb-a96e-4c93-90e3-a159d3060698)

**Comment by mattmarkwick** [comment]
These are linting errors and have no impact on the script running. It is also linting the minified Svelte production code that I published for the script so is out of scope in terms of something I can fix. 

I've just updated my Fooocus and tested and am having no issues - and yes my tampermonkey is also giving the same linting errors. 

Are you using the Fooocus-MRE fork or the original? This script does not currently support the MRE fork. 

Lastly, I notice a link has been added directly to the log 
![image](https://github.com/mattmarkwick/fooocus-gallery/assets/52632226/5d7932eb-875a-4f31-969b-6047d3685d8f)
My script does not currently support loading the log via this link, please instead open the log from your file browser.

**Comment by kkol4anov** [comment]
I'm sorry. It was my fault. I forget to allow access to file URL's. Now it works. Thank you.
I'm using both Fooocus-MRE fork and the original.

Besides, I made small changes to the script locally and now it also works on Fooocus-MRE.
![image](https://github.com/mattmarkwick/fooocus-gallery/assets/39926218/e3354698-5364-4448-9256-bf9a1bf358c3)
