### ISSUE TITLE
Not working for Fooocus 2.1.854?

### ISSUE THREAD

**Issue by ItsNoted** [mattmarkwick/fooocus-gallery#9]
Installed Tampermonkey and installed the script but when I open the log.html file it just shows the standard output html.

![chrome_gUNLm2hby7](https://github.com/mattmarkwick/fooocus-gallery/assets/57927413/dd18d77b-7d79-4124-9829-53a784555567)

**Comment by mattmarkwick** [comment]
Hey there, I've now updated this script to support the latest version, you can update the script from inside Tampermonkey and it will work again.
